name: Run tests

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/UnitTests.yml'
      - 'ext/**'
      - 'src/**'
      - 'test/**'
      - 'Project.toml'
  pull_request:
    paths:
      - '.github/workflows/UnitTests.yml'
      - 'ext/**'
      - 'src/**'
      - 'test/**'
      - 'Project.toml'

# needed to allow julia-actions/cache to delete old caches that it has created
permissions:
  actions: write
  contents: read

concurrency:
  # Skip intermediate builds: always.
  # Cancel intermediate builds: always.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        julia-version:
          - 'min'
          - '1'
          - 'pre'
          - 'nightly'
        julia-arch:
          - default
          - x86
        os:
          - ubuntu-latest
          - windows-latest
          - macOS-latest
        exclude:
          - os: macOS-latest
            julia-arch: x86

    steps:
      - uses: actions/checkout@v5
      - uses: julia-actions/setup-julia@v2
        with:
          version: ${{ matrix.julia-version }}
          arch: ${{ matrix.julia-arch }}
      - uses: julia-actions/cache@v2
      - uses: julia-actions/julia-runtest@v1
